from flask import Flask
from flask import request
from flask import render_template, send_file
import json
import os

app = Flask(__name__)

with open('palworld_default_settings.json', 'r', encoding='utf-8') as f:
    defaults = json.load(f)

escaped_values = []

for section in defaults:
    for setting in section['settings']:
        if setting['setting_type'] != 'number':
            escaped_values.append(setting['setting_name'])
def handle_form(form):
    submit_type = form.get('submitType')
    output_ini = '''; This configuration file is a sample of the default server settings.
; Changes to this file will NOT be reflected on the server.
; To change the server settings, modify Pal/Saved/Config/WindowsServer/PalWorldSettings.ini.
;
; Configuration file generated by https://palconfig.tctcl.dev
;
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,'''

    for k, v in form.items():
        if k != 'submitType':
            if k not in escaped_values or v == 'True' or v == 'False':
                output_ini += k + '=' + v + ','
            else:
                output_ini += k + '="' + v + '",'

    output_ini = output_ini [:-1] + ')'

    file_path = f'generated/{hash(output_ini)}/PalWorldSettings.ini'
    os.makedirs(os.path.dirname(file_path), exist_ok=True)

    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(output_ini)

    return file_path


@app.get('/')
def config_editor():
    return render_template('index.html', defaults=defaults)


@app.post('/')
def generate_config():
    file_path = handle_form(request.form)
    return send_file(file_path, as_attachment=True)


if __name__ == "__main__":
    app.run(host='0.0.0.0')