name: CI

on: [push]

jobs:
  publish-pal-cfg-editor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/tctcl/pal-cfg-editor:latest
        docker run ghcr.io/tctcl/pal-cfg-editor:latest
        docker push ghcr.io/tctcl/pal-cfg-editor:latest
